[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo no build step"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
